[package]
name = "leetcode_rust"
version = "0.1.0"
authors = ["hbina085"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
